# Generated by Django 4.1.5 on 2023-01-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_news_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
                ('tel', models.IntegerField()),
                ('email2', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
            ],
        ),
    ]
